#!/bin/sh

TUNNEL_VERSION_FILE=./tunnel/lib/src/tunnel/version.hpp
TUNNEL_VERSION_MAJOR=$(grep '#define TUNNEL_MAJOR_VERSION' "$TUNNEL_VERSION_FILE" \
    | cut -d' ' -f3)
TUNNEL_VERSION_MINOR=$(grep '#define TUNNEL_MINOR_VERSION' "$TUNNEL_VERSION_FILE" \
    | cut -d' ' -f3)
TUNNEL_VERSION_PATCH=$(grep '#define TUNNEL_PATCH_NUMBER' "$TUNNEL_VERSION_FILE" \
    | cut -d' ' -f3)

TUNNEL_VERSION=$TUNNEL_VERSION_MAJOR.$TUNNEL_VERSION_MINOR.$TUNNEL_VERSION_PATCH
